### ISSUE TITLE
Can't restart the server in dev mode

### ISSUE THREAD

**Issue by tenzai** [yabeda-rb/yabeda-sidekiq#1]
Hi, after i've  seted up my gemfile with the Yabeda Suite using this lines 
`gem 'yabeda'`
`gem 'yabeda-rails'`
`gem 'yabeda-sidekiq'`
but when i tried to start my server in my local machine the console throws me 👍 
`/Users/felipealvarado/.rvm/gems/ruby-2.3.3/gems/yabeda-0.1.1/lib/yabeda/dsl.rb:45:in `register': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /Users/felipealvarado/.rvm/gems/ruby-2.3.3/gems/yabeda-0.1.1/lib/yabeda/dsl.rb:29:in `counter'
	from /Users/felipealvarado/.rvm/gems/ruby-2.3.3/gems/yabeda-sidekiq-0.1.2/lib/yabeda/sidekiq.rb:20:in `block in <module:Sidekiq` among other lines... 

What i've missed ?

**Comment by Envek** [comment]
Hi @tenzai and thank you for your interest!

Please try to upgrade to yabeda 0.1.2 and yabeda-sidekiq 0.1.3 — there fixed some minor things.

If the problem still persists, please provide more info (self-contained gist with inline gemfile would be awesome).

**Comment by tenzai** [comment]
@Envek it's alive !!!!!!!!! just upgrade to yabeda 0.1.2 and yabeda-sidekiq 0.1.3 and its done !
