### ISSUE TITLE
NoMethodError: undefined method `sidekiq_jobs_enqueued_total' for Yabeda:Module

### ISSUE THREAD

**Issue by inderps** [yabeda-rb/yabeda-sidekiq#10]
I'm running
'rails', '4.2.9'
sidekiq (5.2.7)

And I get following error

![Bildschirmfoto 2020-02-28 um 16 12 31](https://user-images.githubusercontent.com/1210046/75560374-50057680-5a45-11ea-8e2e-a176d46daaeb.png)

**Comment by Envek** [comment]
Hi, @inderps. Are you using gem [yabeda-rails](https://github.com/yabeda-rb/yabeda-rails) or is there only `gem "yabeda-sidekiq"` in your Gemfile?

Please try to add `gem "yabeda-rails"` to your Gemfile. I believe that it should fix the error.

**Comment by inderps** [comment]
@Envek Thanks for your quick reply. Yes I discovered that to use yabeda-sidekiq, you need to add yabeda-rails as well. But by adding yabeda rails, will it also create metrics for web app? Because in our case, we were interested in sidekiq only.

**Comment by Envek** [comment]
If you don't want web metrics, you can just copy this railtie to your application: https://github.com/yabeda-rb/yabeda-rails/blob/master/lib/yabeda/rails/railtie.rb

I will add necessary configs and documentation later.

**Comment by inderps** [comment]
Alright thanks

**Comment by hallelujah** [comment]
I think the simple fix would be to call:

```ruby
Yabeda.configure! unless Yabeda.already_configured?
``` 

Like in https://github.com/yabeda-rb/yabeda-rails/blob/583b476e0a26ece08f3abefb1b423d5576837748/lib/yabeda/rails/railtie.rb#L18-L21

**Comment by hallelujah** [comment]
@inderps why do you close the issue?

The gem does not work out of the box on standalone sidekiq.
It would be nice to have at least an instruction in the README
