### ISSUE TITLE
Wrong numbers reported

### ISSUE THREAD

**Issue by mbajur** [yabeda-rb/yabeda-sidekiq#16]
Hello!
I'm trying to create a proper bug report but there are so many moving parts in here that I'm not even sure where to start. Let's start with the basics - amount of enqueued jobs. In my sidekiq UI, i can see there are ~8k enqueued jobs but my grafana dashboard shows 3. Query settings looks as follows:

![image](https://user-images.githubusercontent.com/581569/107766958-91656380-6d34-11eb-8f82-29205b06a4b0.png)

On the other hand, i have the exact same query created for retries and it calculates retries just fine.

My stack is: sidekiq 4.2, yabeda-sidekiq 0.7, telegraf + influxdb + grafana. First of all - does this query look proper for the way yabeda-sidekiq reports this specific metric? 

It's super hard to say if that's yabeda-sidekiq fault or my grafana queries fault. If there is anything i can do to help you help me, please just let me know :)

Thanks in advance!

**Comment by Envek** [comment]
Hi! Yeah, a lot of things here and its overwhelming, I know.

> amount of enqueued jobs.

If you're talking about number of jobs that are waiting in queues to be executed then you need `sidekiq_jobs_waiting_count` gauge. And formula should be something like `max(sidekiq_jobs_waiting_count) by (queue)` to handle differences in gauge values reported by different sidekiq workers.

`sidekiq_jobs_enqueued_total` is a counter of job enqueue events to keep track of which processes enqueues which jobs (e.g. how many jobs are being enqueued from app servers or rake tasks or other sidekiq jobs). It is not useful for you, I believe.

**Comment by mbajur** [comment]
Ha! @Envek that was it, metric name tricked me :) thank you so much!
