### ISSUE TITLE
uninitialized constant Sidekiq::Job on Sidekiq v6.2.2

### ISSUE THREAD

**Issue by shouichi** [yabeda-rb/yabeda-sidekiq#24]
It seems like the class was renamed.

> Rename internal API class Sidekiq::Job to Sidekiq::JobRecord [#4955]

https://github.com/mperham/sidekiq/blob/8e36432662421e79cf14096e9467666b6827f82d/Changes.md

**Comment by Envek** [comment]
Thank you for pointing this out! Fix has been released in [0.8.1](https://github.com/yabeda-rb/yabeda-sidekiq/releases/tag/v0.8.1)

**Comment by shouichi** [comment]
Thank you for this nice project, it's been super beneficial for us 👍
