### ISSUE TITLE
[Sidekiq Enterprise] Export `collect_cluster_metrics` only on `leader` node.

### ISSUE THREAD

**Issue by hbontempo-cw** [yabeda-rb/yabeda-sidekiq#36]
Sidekiq Enterprise has a single [`leader`](https://github.com/sidekiq/sidekiq/wiki/Ent-Leader-Election) node.
To avoid making unnecessary requests and work from multiples nodes we could extract the metrics only from the leader node.
[Feature similar to the feature available throughout the flag `global_metrics_enabled` of [`fastly/sidekiq-prometheus`](https://github.com/fastly/sidekiq-prometheus)]

What you think? Are you willing to add a SidekiqEnterprise specific feature?

At first glance it should not be very difficult to implement.
The cluster metrics would need to be registered no matter if the node is a leader or not (since for exportes like Prometheus we can't change the metrics at any time). 
And each time the `collect` block the code would need to check if the installation is an Enterprise one (`::Sidekiq.ent?`) and if so check if the current node is the leader (with method `#leader?` once including the module `::Sidekiq::Component`)

ps: I did a dirt-fast implementation (just updating the `Yabeda::Sidekiq.config.collect_cluster_metrics` config depending if the node is the leader every 15 seconds)  to see how the metrics are behaving, specially when a new leader is elected, and everything seams fine...

```ruby
# config/initializers/yabeda.rb

Yabeda.configure do
  default_tag :app_version, ENV['APP_VERSION']
  group :sidekiq do
    default_tag :leader, 'false'
  end
end

# Basically a copy/paste of: https://github.com/sidekiq/sidekiq/wiki/Ent-Leader-Election
class Yabeda::Sidekiq::LeaderMonitor
  include ::Sidekiq::Component

  def initialize(config)
    @config = config
    @done = false
  end

  def start
    @thread = safe_thread("yabeda_sidekiq_leadermonitor", &method(:process))
  end

  def stop
    @done = true
  end

  private

  def process
    until @done
      leader = leader?
      Yabeda::Sidekiq.config.collect_cluster_metrics = leader
      Yabeda.groups[:sidekiq].default_tag :leader, leader
      sleep 15
    end
  end
end

Sidekiq.configure_server do |config|
  config.on(:startup) do
    config.lookup("yabeda_sidekiq_leadermonitor", Yabeda::Sidekiq::LeaderMonitor).start
  end
  config.on(:quiet) do
    config.lookup("yabeda_sidekiq_leadermonitor")&.stop
  end
end

if ActiveModel::Type::Boolean.new.cast(ENV['YABEDA_PROMETHEUS']) == true
  Yabeda::Prometheus::Exporter.start_metrics_server!
end
```

**Comment by Envek** [comment]
Hey, thanks for the proposal. Yes, I'm all for adding Sidekiq Enterprise support.

The only thing in your current implementation that is worrying me is that (in case of Prometheus) after some worker node stepped down from a leader position, it will stop collecting new values from Redis but will continue to export stale values to Prometheus on every scrape.

Current `collect_cluster_metrics` setting was made to allow setup of separate “metrics exporter process” (maybe not Sidekiq one at all but application-wide one) to reduce load on Redis from dozens of worker processes (as there is no leader in OSS Sidekiq).

**Comment by hbontempo-cw** [comment]
> The only thing in your current implementation that is worrying me is that (in case of Prometheus) after some worker node stepped down from a leader position, it will stop collecting new values from Redis but will continue to export stale values to Prometheus on every scrape.

Yes, this is a problem, in my monitoring I filtering metrics only from the `leader` tag but I understand that It's not a solution (I'm just ignoring problem). 
A solution would probably require to somehow "unregister" a metric... This makes the problem is way more complicated than I initially thought.

>  setup of separate  “metrics exporter process” (maybe not Sidekiq one at all but application-wide one)

Of course! There is no reason why this metrics could not be exported by another process! 
Looking at the problem this way makes things far simpler than what I was making it...
(specially in my specific case where I'm looking forward to scale process down to 0 depending on the extracted method...)

---

I'm closing the issue because I realized that this feature I requested is basically solving a problem that don't really exist (it's a "nice to have" feature at best).

Thanks @Envek for taking the time to answer my request (and for the awesome tools you work on)
